language: php
php:
- 7.1.9
script: true
notifications:
  email:
    recipients:
    - fsyzxz@163.com
    on_success: change
    on_failure: always
after_success:
- ssh root@47.106.88.123 './travis_build'
before_install:
  - openssl aes-256-cbc -K $encrypted_29815ebf6ec4_key -iv $encrypted_29815ebf6ec4_iv
    -in id_rsa.enc -out ~/Desktop/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 47.106.88.123